### ISSUE TITLE
Confusing nimble

### ISSUE THREAD

**Issue by TakWolf** [TakWolf/nico-font-tool#10]
https://github.com/nim-lang/packages/pull/2608

**Comment by TakWolf** [comment]
https://github.com/nim-lang/packages/pull/2608

**Comment by TakWolf** [comment]
> Warning: Package 'nico_font_tool' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'nico_font_tool', but file 'test_demo.nim' is in a directory named 'tests' instead. This will be an error in the future.
> Hint: If 'tests' contains source files for building 'nico_font_tool', rename it to 'nico_font_tool'. Otherwise, prevent its installation by adding `skipDirs = @["tests"]` to the .nimble file.

https://github.com/TakWolf/nico-font-tool/blob/master/nico_font_tool.nimble#L1-L16


```
# Package

version       = "0.0.2"
author        = "TakWolf"
description   = "A tool for converting fonts to NICO Game Framework format fonts."
license       = "MIT"

skipDirs      = @["tests", "examples"]       # <--------------???
installExt    = @["nim"]
bin           = @["nicofont"]

# Dependencies

requires "nim >= 1.4.0"
requires "pixie >= 5.0.6"
requires "nimPNG >= 0.3.2"
```


![image](https://github.com/TakWolf/nico-font-tool/assets/6064962/16ed0394-a6ec-4fd5-b5d8-7ecc900a7eba)

**Comment by Angluca** [comment]
https://github.com/TakWolf/nico-font-tool/pull/11
